# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  name: get-pr
  description: Get the PR info by ID or associated commit
  homepage: https://cloudposse.com/accelerate
  topics: "github-action"
