name: PR Info
author: 8BitJonny
description: Get the PR info associated with the current commit.
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.
    required: false
    default: ${{ github.token }}
  sha:
    description: Sha to get PR for. Defaults to current sha.
    required: false
  filterOutClosed:
    description: True, False, 1 or 0 if only open PRs should be returned. Defaults to false.
    required: false
  filterOutDraft:
    description: True, False, 1 or 0 if only non-draft PRs should be returned. Defaults to false.
    required: false
outputs:
  found:
    description: The outcome if a PR has been found. If so, the other outputs are set.
  json:
    description: The whole PR object if one was found.
  number:
    description: The PR number if one was found.
  title:
    description: The PR Title if one was found.
  body:
    description: The PR Body if one was found.
  url:
    description: The PR Url if one was found.
  created_at:
    description: The PR Created timestamp if one was found.
  merged_at:
    description: The PR Merged timestamp if one was found.
  closed_at:
    description: The PR Closed timestamp if one was found.
  labels:
    description: The PR Labels if any was found.
runs:
  using: node20
  main: 'dist/index.js'
branding:
  icon: git-pull-request
  color: white
